repos:
  - repo: https://github.com/tofuutils/pre-commit-opentofu
    rev: v2.2.2
    hooks:
      - id: tofu_fmt

  - repo: local
    hooks:
      - id: terraform-docs
        name: terraform-docs
        entry: >-
          mise exec -- terraform-docs markdown table
          --recursive
          --recursive-path modules
          --output-file README.md
          --output-mode inject
          src
        language: system
        pass_filenames: false
        files: ^src/.*\.(tf|tofu|terraform\.lock\.hcl)$
