#!/usr/bin/env python3
"""Export a reviewed semantic subset for digits/light; never merge other themes."""
import json
import re
from pathlib import Path

base = Path(__file__).resolve().parents[2]
groups = json.loads((base / '.local/portal-reference/design-tokens.json').read_text())['groups']
base_values = {}
for group in groups:
    if group['selector'] in ('html', 'html.brand--digits', 'html.theme--light'):
        base_values.update(group['declarations'])

names = [
    'color-background-neutral-surface-raised-rest', 'color-background-neutral-surface-sunken-rest',
    'color-background-neutral-surface-selected-rest', 'color-background-header-surface-rest',
    'color-background-cta-rest', 'color-background-cta-hover', 'color-background-cta-active',
    'color-foreground-on-cta-default', 'color-foreground-neutral-default',
    'color-foreground-neutral-high-contrast', 'color-foreground-neutral-selected',
    'color-border-neutral-default-rest', 'color-border-neutral-subtle-rest', 'color-border-focus',
    'color-background-negative-surface-rest', 'color-foreground-negative-on-subtle',
    'color-background-positive-surface-rest', 'color-foreground-positive-on-neutral',
    'color-background-informative-surface-rest', 'color-foreground-informative-on-neutral',
    'font-family-body', 'font-family-heading',
]
mode_names = ['--nds-mode-' + name for name in names]
viewport_names = ['--nds-viewport-' + name for name in [
    'font-size-body-default', 'font-size-body-small', 'font-size-body-large',
    'font-size-button', 'font-size-input', 'font-size-label-small', 'font-size-label-default',
    'font-size-heading-content-level-1', 'font-size-heading-content-level-2',
    'font-size-heading-content-level-3', 'border-radius-component-medium', 'border-radius-component-small',
]]

def resolved(name, values, depth=0):
    if depth > 20:
        raise ValueError('Cyclic token reference')
    return re.sub(r'var\(\s*(--[\w-]+)\s*\)', lambda m: resolved(m[1], values, depth + 1), values[name]).strip()

def declarations(names, values):
    return '\n'.join('  ' + name + ': ' + resolved(name, values) + ';' for name in names)

css = '''/* Generated by tools/portal-reference/export-tokens.py.
 * Source: portal styles-HOVMV7T5.css, 2026-09-30, digits/light only.
 * Selected semantic values resolved from the original scoped declarations.
 * See docs/design-reference.md; this is not the Nebula component library.
 */\n:root {\n'''
css += declarations(mode_names, base_values) + '\n}\n'
for group in groups:
    selector = group['selector']
    if selector.startswith('@media') and selector.endswith('{html'):
        values = {**base_values, **group['declarations']}
        media = selector.removesuffix('{html')
        css += media + ' {\n:root {\n' + declarations(viewport_names, values) + '\n}\n}\n'
(base / 'app/apps/web/src/nebula-tokens.css').write_text(css)
