import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, writeFileSync, readFileSync, statSync, rmSync, existsSync, mkdirSync, symlinkSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { approvedReleaseSource, createReleaseManifest, verifyReleaseManifest } from "./release-artifact.mjs";
const script=fileURLToPath(new URL("./prepare-release.mjs",import.meta.url));
test("one release manifest binds both packages to the same immutable build",()=>{
 const directory=mkdtempSync(join(tmpdir(),"lzc-release-artifact-test-"));
 const source={revision:"a".repeat(40),runId:"12345"};
 try {
  writeFileSync(join(directory,"release.tar.gz"),"compiled application and migrations");
  writeFileSync(join(directory,"runner.tar.gz"),"isolated pinned runner");
  const manifest=createReleaseManifest(directory,source);
  assert.deepEqual(verifyReleaseManifest(directory,source),manifest);
  assert.throws(()=>createReleaseManifest(directory,source));
  assert.throws(()=>verifyReleaseManifest(directory,{...source,revision:"b".repeat(40)}));
  assert.throws(()=>verifyReleaseManifest(directory,{...source,runId:"54321"}));
  writeFileSync(join(directory,"runner.tar.gz"),"changed runner");
  assert.throws(()=>verifyReleaseManifest(directory,source),/checksum mismatch/);
 }finally{rmSync(directory,{recursive:true,force:true});}
});
test("promotion requires the successful build's exact repository, source and immutable artifact",()=>{
 const run={id:12345,run_attempt:1,path:".github/workflows/configurator-release.yml",head_sha:"a".repeat(40),head_repository:{full_name:"stackitcloud/stackit-landing-zone"},head_branch:"feature/landing-zone-configurator",event:"workflow_dispatch"};
 const jobs=[{name:"build",status:"completed",conclusion:"success"}];
 const artifact={id:67890,name:"configurator-release-12345",expired:false,workflow_run:{id:12345,head_sha:run.head_sha}};
 assert.deepEqual(approvedReleaseSource(run,jobs,[artifact],"12345"),{revision:run.head_sha,runId:"12345",artifactId:"67890"});
 for(const changed of [{...run,event:"pull_request"},{...run,head_repository:{full_name:"someone/fork"}},{...run,path:".github/workflows/other.yml"},{...run,head_branch:"unapproved"},{...run,run_attempt:2}])
  assert.throws(()=>approvedReleaseSource(changed,jobs,[artifact],"12345"));
 assert.throws(()=>approvedReleaseSource(run,[],[artifact],"12345"));
 assert.throws(()=>approvedReleaseSource(run,[{...jobs[0],conclusion:"failure"}],[artifact],"12345"));
 assert.throws(()=>approvedReleaseSource(run,jobs,[{...artifact,expired:true}],"12345"));
 assert.throws(()=>approvedReleaseSource(run,jobs,[{...artifact,workflow_run:{id:12345,head_sha:"b".repeat(40)}}],"12345"));
 assert.throws(()=>approvedReleaseSource(run,jobs,[artifact,artifact],"12345"));
});
test("release uses private inputs, rejects wrong destinations and omits privileged credentials",()=>{
 const dir=mkdtempSync(join(tmpdir(),"lzc-release-test-"));
 const env={...process.env,GITHUB_REPOSITORY:"stackitcloud/stackit-landing-zone",GITHUB_REF:"refs/heads/feature/landing-zone-configurator",RUNNER_TEMP:dir,GITHUB_ENV:join(dir,"environment"),LZC_WORKLOAD_BUCKET:"lzc-dev-state-7dbff805",LZC_STATE_KEY_PLATFORM:"p".repeat(40),LZC_STATE_KEY_RUNTIME:"r".repeat(40),LZC_WORKLOAD_ACCESS_KEY:"test-access",LZC_WORKLOAD_SECRET_KEY:"test-secret"};
 const artifactApi=join(dir,".local/release/apps/api");mkdirSync(artifactApi,{recursive:true});
 symlinkSync(fileURLToPath(new URL("../../app/apps/api/dist",import.meta.url)),join(artifactApi,"dist"),"dir");
 const run=mode=>spawnSync(process.execPath,[script,mode],{env,cwd:dir,encoding:"utf8"});
 Object.assign(env,{LZC_AUTH_ENABLED:"false",LZC_STACKIT_DEVICE_ENABLED:"false",LZC_STACKIT_CLI_CLIENT_APPROVED:"false",LZC_GITHUB_CLIENT_ID:"",LZC_GITHUB_CLIENT_SECRET:""});
 try {
  assert.equal(run("backend").status,0);
  const privateDir=join(dir,"lzc-release");
  const cf={api_url:"https://api.system.01.cf.eu01.stackit.cloud",org_id:"a4514c42-d378-4e36-90eb-a3a1e3017e65",username:"cf-user",password:"cf-secret"};
  writeFileSync(join(privateDir,"platform-outputs.json"),JSON.stringify({cf_runtime:{value:cf},database_migration:{value:{host:"test-LZC_DATABASE_HOST",port:"test-LZC_DATABASE_PORT",database:"configurator",username:"configurator_migration",password:"migration-only-secret"}}}));
  const keys=["LZC_DATABASE_HOST","LZC_DATABASE_PORT","LZC_DATABASE_NAME","LZC_DATABASE_USER","LZC_DATABASE_PASSWORD","LZC_SECRETS_ADDRESS","LZC_SECRETS_INSTANCE_ID","LZC_SECRETS_USERNAME","LZC_SECRETS_PASSWORD","LZC_MODEL_SERVING_TOKEN"];
  const runtime={space:{value:{id:"space-guid",name:"wrong-space"}},app_environment:{value:Object.fromEntries(keys.map(key=>[key,`test-${key}`]))}};
  runtime.app_environment.value.LZC_SERVICE_ACCOUNT_KEY="must-not-be-forwarded";
  writeFileSync(join(privateDir,"runtime-outputs.json"),JSON.stringify(runtime));
  assert.notEqual(run("application").status,0);
  assert.equal(existsSync(join(privateDir,"app-vars.json")),false);
  runtime.space.value.name="configurator";
  writeFileSync(join(privateDir,"runtime-outputs.json"),JSON.stringify(runtime));
  const result=run("application");assert.equal(result.status,0,result.stderr);
  const vars=join(privateDir,"app-vars.json");assert.equal(statSync(vars).mode&0o777,0o600);
  const app=JSON.parse(readFileSync(vars));
    assert.deepEqual(Object.keys(app),[...keys,"LZC_AUTH_ENABLED","LZC_STACKIT_DEVICE_ENABLED","LZC_STACKIT_CLI_CLIENT_APPROVED","LZC_PUBLIC_ORIGIN","LZC_GITHUB_CLIENT_ID","LZC_GITHUB_CLIENT_SECRET","LZC_STACKIT_AUTH_FLOW","LZC_STACKIT_CLIENT_ID","LZC_STACKIT_REDIRECT_URI","LZC_PLANS_ENABLED","LZC_RUNNER_CF_USERNAME","LZC_RUNNER_CF_PASSWORD","LZC_RUNNER_SPACE_ID","LZC_RUNNER_TEMPLATE_ID"]);
  assert.equal(app.LZC_AUTH_ENABLED,"false");
    assert.equal(app.LZC_STACKIT_DEVICE_ENABLED,"false");
    assert.equal(app.LZC_STACKIT_CLI_CLIENT_APPROVED,"false");
  assert.equal(app.LZC_GITHUB_CLIENT_SECRET,"");
  assert.ok(!readFileSync(vars,"utf8").includes("migration-only-secret"));
  const migration=join(privateDir,"migration-vars.json");
  assert.equal(statSync(migration).mode&0o777,0o600);
  const migrationValues=JSON.parse(readFileSync(migration));
  assert.equal(migrationValues.LZC_DATABASE_USER,"configurator_migration");
  assert.equal(migrationValues.LZC_DATABASE_PASSWORD,"migration-only-secret");
  assert.equal(Object.keys(migrationValues).length,5);
  env.LZC_AUTH_ENABLED="true";
  assert.notEqual(run("application").status,0);
  env.LZC_GITHUB_CLIENT_ID="test-client";
  env.LZC_GITHUB_CLIENT_SECRET="test-oauth-secret";
  assert.equal(run("application").status,0);
  const authenticated=JSON.parse(readFileSync(vars));
  assert.equal(authenticated.LZC_AUTH_ENABLED,"true");
  assert.equal(authenticated.LZC_GITHUB_CLIENT_SECRET,"test-oauth-secret");
    env.LZC_STACKIT_DEVICE_ENABLED="true";
    assert.notEqual(run("application").status,0,"must reject unapproved CLI client use");
    env.LZC_STACKIT_CLI_CLIENT_APPROVED="true";
    env.LZC_GITHUB_CLIENT_ID="";
    env.LZC_GITHUB_CLIENT_SECRET="";
    assert.notEqual(run("application").status,0,"must reject missing PKCE configuration before staging");
    env.LZC_STACKIT_CLI_CLIENT_APPROVED="false";
    env.LZC_STACKIT_AUTH_FLOW="authorization-code";
    env.LZC_STACKIT_CLIENT_ID="registered-web-client";
    env.LZC_STACKIT_REDIRECT_URI="https://lzc-dev-configurator-7dbff805.apps.01.cf.eu01.stackit.cloud/auth/stackit/callback";
    assert.equal(run("application").status,0,"STACKIT login must not require GitHub");
    const stackit=JSON.parse(readFileSync(vars));
    assert.equal(stackit.LZC_STACKIT_DEVICE_ENABLED,"true");
    assert.equal(stackit.LZC_STACKIT_CLI_CLIENT_APPROVED,"false");
    assert.equal(stackit.LZC_GITHUB_CLIENT_SECRET,"");
    assert.equal(stackit.LZC_STACKIT_AUTH_FLOW,"authorization-code");
    assert.equal(stackit.LZC_STACKIT_CLIENT_ID,"registered-web-client");
    env.LZC_STACKIT_CLIENT_ID="stackit-cli-0000-0000-000000000001";
    assert.notEqual(run("application").status,0,"must reject an unregistered hosted CLI callback");
    env.LZC_STACKIT_CLIENT_ID="registered-web-client";
    env.LZC_GITHUB_CLIENT_ID="test-client";
    assert.notEqual(run("application").status,0,"must reject incomplete optional GitHub credentials");
    env.LZC_GITHUB_CLIENT_SECRET="test-oauth-secret";
    env.LZC_AUTH_ENABLED="false";
    assert.notEqual(run("application").status,0,"must reject STACKIT login without authentication");
    env.LZC_AUTH_ENABLED="true";
    env.LZC_STACKIT_DEVICE_ENABLED="false";
    env.LZC_STACKIT_CLI_CLIENT_APPROVED="false";
    assert.equal(run("application").status,0);
  assert.ok(!readFileSync(migration,"utf8").includes("test-oauth-secret"));
  assert.ok(!readFileSync(env.GITHUB_ENV,"utf8").includes("must-not-be-forwarded"));
  assert.equal(authenticated.LZC_PLANS_ENABLED,"false");
  assert.notEqual(run("runner").status,0);
  const platform=JSON.parse(readFileSync(join(privateDir,"platform-outputs.json")));
  platform.plan_runner_cf={value:{api_url:cf.api_url,org_id:cf.org_id,username:"runner-user",password:"runner-only-secret"}};
  runtime.runner_space={value:{id:"11111111-1111-4111-8111-111111111111",name:"plans",org_id:cf.org_id}};
  writeFileSync(join(privateDir,"platform-outputs.json"),JSON.stringify(platform));
  writeFileSync(join(privateDir,"runtime-outputs.json"),JSON.stringify(runtime));
  assert.notEqual(run("application").status,0,"must reject shared app/runner organisation");
  platform.plan_runner_cf.value.org_id="22222222-2222-4222-8222-222222222222";
  runtime.runner_space.value.org_id=platform.plan_runner_cf.value.org_id;
  writeFileSync(join(privateDir,"platform-outputs.json"),JSON.stringify(platform));
  writeFileSync(join(privateDir,"runtime-outputs.json"),JSON.stringify(runtime));
  assert.equal(run("application").status,0);
  env.LZC_RUNNER_TEMPLATE_ID="33333333-3333-4333-8333-333333333333";
  assert.equal(run("runner").status,0);
  const enabled=JSON.parse(readFileSync(vars));
  assert.equal(enabled.LZC_PLANS_ENABLED,"true");
  assert.equal(enabled.LZC_RUNNER_CF_PASSWORD,"runner-only-secret");
  assert.ok(!readFileSync(migration,"utf8").includes("runner-only-secret"));

 } finally {rmSync(dir,{recursive:true,force:true});}
});
