import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, writeFileSync, readFileSync, statSync, rmSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
const script=fileURLToPath(new URL("./prepare-release.mjs",import.meta.url));
test("release uses private inputs, rejects wrong destinations and omits privileged credentials",()=>{
 const dir=mkdtempSync(join(tmpdir(),"lzc-release-test-"));
 const env={...process.env,GITHUB_REPOSITORY:"stackitcloud/stackit-landing-zone",GITHUB_REF:"refs/heads/feature/landing-zone-configurator",RUNNER_TEMP:dir,GITHUB_ENV:join(dir,"environment"),LZC_WORKLOAD_BUCKET:"lzc-dev-state-7dbff805",LZC_STATE_KEY_PLATFORM:"p".repeat(40),LZC_STATE_KEY_RUNTIME:"r".repeat(40),LZC_WORKLOAD_ACCESS_KEY:"test-access",LZC_WORKLOAD_SECRET_KEY:"test-secret"};
 const run=mode=>spawnSync(process.execPath,[script,mode],{env,encoding:"utf8"});
 Object.assign(env,{LZC_AUTH_ENABLED:"false",LZC_STACKIT_DEVICE_ENABLED:"false",LZC_STACKIT_CLI_CLIENT_APPROVED:"false",LZC_GITHUB_CLIENT_ID:"",LZC_GITHUB_CLIENT_SECRET:""});
 try {
  assert.equal(run("backend").status,0);
  const privateDir=join(dir,"lzc-release");
  const cf={api_url:"https://api.system.01.cf.eu01.stackit.cloud",org_id:"a4514c42-d378-4e36-90eb-a3a1e3017e65",username:"cf-user",password:"cf-secret"};
  writeFileSync(join(privateDir,"platform-outputs.json"),JSON.stringify({cf_runtime:{value:cf},database_migration:{value:{host:"test-LZC_DATABASE_HOST",port:"test-LZC_DATABASE_PORT",database:"configurator",username:"configurator_migration",password:"migration-only-secret"}}}));
  const keys=["LZC_DATABASE_HOST","LZC_DATABASE_PORT","LZC_DATABASE_NAME","LZC_DATABASE_USER","LZC_DATABASE_PASSWORD","LZC_SECRETS_ADDRESS","LZC_SECRETS_INSTANCE_ID","LZC_SECRETS_USERNAME","LZC_SECRETS_PASSWORD","LZC_MODEL_SERVING_TOKEN"];
  const runtime={space:{value:{id:"space-guid",name:"wrong-space"}},app_environment:{value:Object.fromEntries(keys.map(key=>[key,`test-${key}`]))}};
  runtime.app_environment.value.LZC_SERVICE_ACCOUNT_KEY="must-not-be-forwarded";
  writeFileSync(join(privateDir,"runtime-outputs.json"),JSON.stringify(runtime));
  assert.notEqual(run("application").status,0);
  assert.equal(existsSync(join(privateDir,"app-vars.json")),false);
  runtime.space.value.name="configurator";
  writeFileSync(join(privateDir,"runtime-outputs.json"),JSON.stringify(runtime));
  const result=run("application");assert.equal(result.status,0,result.stderr);
  const vars=join(privateDir,"app-vars.json");assert.equal(statSync(vars).mode&0o777,0o600);
  const app=JSON.parse(readFileSync(vars));
    assert.deepEqual(Object.keys(app),[...keys,"LZC_AUTH_ENABLED","LZC_STACKIT_DEVICE_ENABLED","LZC_STACKIT_CLI_CLIENT_APPROVED","LZC_PUBLIC_ORIGIN","LZC_GITHUB_CLIENT_ID","LZC_GITHUB_CLIENT_SECRET","LZC_PLANS_ENABLED","LZC_RUNNER_CF_USERNAME","LZC_RUNNER_CF_PASSWORD","LZC_RUNNER_SPACE_ID","LZC_RUNNER_TEMPLATE_ID"]);
  assert.equal(app.LZC_AUTH_ENABLED,"false");
    assert.equal(app.LZC_STACKIT_DEVICE_ENABLED,"false");
    assert.equal(app.LZC_STACKIT_CLI_CLIENT_APPROVED,"false");
  assert.equal(app.LZC_GITHUB_CLIENT_SECRET,"");
  assert.ok(!readFileSync(vars,"utf8").includes("migration-only-secret"));
  const migration=join(privateDir,"migration-vars.json");
  assert.equal(statSync(migration).mode&0o777,0o600);
  const migrationValues=JSON.parse(readFileSync(migration));
  assert.equal(migrationValues.LZC_DATABASE_USER,"configurator_migration");
  assert.equal(migrationValues.LZC_DATABASE_PASSWORD,"migration-only-secret");
  assert.equal(Object.keys(migrationValues).length,5);
  env.LZC_AUTH_ENABLED="true";
  assert.notEqual(run("application").status,0);
  env.LZC_GITHUB_CLIENT_ID="test-client";
  env.LZC_GITHUB_CLIENT_SECRET="test-oauth-secret";
  assert.equal(run("application").status,0);
  const authenticated=JSON.parse(readFileSync(vars));
  assert.equal(authenticated.LZC_AUTH_ENABLED,"true");
  assert.equal(authenticated.LZC_GITHUB_CLIENT_SECRET,"test-oauth-secret");
    env.LZC_STACKIT_DEVICE_ENABLED="true";
    assert.notEqual(run("application").status,0,"must reject unapproved CLI client use");
    env.LZC_STACKIT_CLI_CLIENT_APPROVED="true";
    env.LZC_GITHUB_CLIENT_ID="";
    env.LZC_GITHUB_CLIENT_SECRET="";
    assert.equal(run("application").status,0,"STACKIT login must not require GitHub");
    const stackit=JSON.parse(readFileSync(vars));
    assert.equal(stackit.LZC_STACKIT_DEVICE_ENABLED,"true");
    assert.equal(stackit.LZC_STACKIT_CLI_CLIENT_APPROVED,"true");
    assert.equal(stackit.LZC_GITHUB_CLIENT_SECRET,"");
    env.LZC_GITHUB_CLIENT_ID="test-client";
    assert.notEqual(run("application").status,0,"must reject incomplete optional GitHub credentials");
    env.LZC_GITHUB_CLIENT_SECRET="test-oauth-secret";
    env.LZC_AUTH_ENABLED="false";
    assert.notEqual(run("application").status,0,"must reject STACKIT login without authentication");
    env.LZC_AUTH_ENABLED="true";
    env.LZC_STACKIT_DEVICE_ENABLED="false";
    env.LZC_STACKIT_CLI_CLIENT_APPROVED="false";
    assert.equal(run("application").status,0);
  assert.ok(!readFileSync(migration,"utf8").includes("test-oauth-secret"));
  assert.ok(!readFileSync(env.GITHUB_ENV,"utf8").includes("must-not-be-forwarded"));
  assert.equal(authenticated.LZC_PLANS_ENABLED,"false");
  assert.notEqual(run("runner").status,0);
  const platform=JSON.parse(readFileSync(join(privateDir,"platform-outputs.json")));
  platform.plan_runner_cf={value:{api_url:cf.api_url,org_id:cf.org_id,username:"runner-user",password:"runner-only-secret"}};
  runtime.runner_space={value:{id:"11111111-1111-4111-8111-111111111111",name:"plans",org_id:cf.org_id}};
  writeFileSync(join(privateDir,"platform-outputs.json"),JSON.stringify(platform));
  writeFileSync(join(privateDir,"runtime-outputs.json"),JSON.stringify(runtime));
  assert.notEqual(run("application").status,0,"must reject shared app/runner organisation");
  platform.plan_runner_cf.value.org_id="22222222-2222-4222-8222-222222222222";
  runtime.runner_space.value.org_id=platform.plan_runner_cf.value.org_id;
  writeFileSync(join(privateDir,"platform-outputs.json"),JSON.stringify(platform));
  writeFileSync(join(privateDir,"runtime-outputs.json"),JSON.stringify(runtime));
  assert.equal(run("application").status,0);
  env.LZC_RUNNER_TEMPLATE_ID="33333333-3333-4333-8333-333333333333";
  assert.equal(run("runner").status,0);
  const enabled=JSON.parse(readFileSync(vars));
  assert.equal(enabled.LZC_PLANS_ENABLED,"true");
  assert.equal(enabled.LZC_RUNNER_CF_PASSWORD,"runner-only-secret");
  assert.ok(!readFileSync(migration,"utf8").includes("runner-only-secret"));

 } finally {rmSync(dir,{recursive:true,force:true});}
});
