import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, writeFileSync, readFileSync, statSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
const script=fileURLToPath(new URL("./prepare.mjs",import.meta.url));
const base={LZC_ROOT:"platform",LZC_ENVIRONMENT:"lzc-dev",GITHUB_REF:"refs/heads/feature/landing-zone-configurator",GITHUB_EVENT_NAME:"push",GITHUB_RUN_ATTEMPT:"1",GITHUB_SHA:"a".repeat(40),LZC_PROJECT_ID:"00000000-0000-4000-8000-000000000001",LZC_REGION:"eu01",LZC_NAME_PREFIX:"lzc-dev",LZC_MANAGEMENT_BUCKET:"lzc-dev-management-00000000",LZC_CREDENTIAL_EXPIRATION:"2026-12-28T00:00:00Z",GITHUB_REPOSITORY:"stackitcloud/stackit-landing-zone",GITHUB_RUN_ID:"123",LZC_SERVICE_ACCOUNT_KEY:'{"test":"fake"}',LZC_MANAGEMENT_ACCESS_KEY:"management-access",LZC_MANAGEMENT_SECRET_KEY:"management-secret",LZC_STATE_KEY_BOOTSTRAP:"b".repeat(40),LZC_STATE_KEY_BACKEND:"c".repeat(40),LZC_STATE_KEY_PLATFORM:"p".repeat(40)};
function fixture(fn){const dir=mkdtempSync(join(tmpdir(),"lzc-prepare-"));const env={...process.env,...base,RUNNER_TEMP:dir,GITHUB_ENV:join(dir,"env")};try{fn(dir,env,(mode,patch={})=>spawnSync(process.execPath,[script,mode],{cwd:dir,env:{...env,...patch},encoding:"utf8"}));}finally{rmSync(dir,{recursive:true,force:true});}}
function exported(path){const text=readFileSync(path,"utf8"),result={};const lines=text.split("\n");for(let i=0;i<lines.length;i++){if(!lines[i])continue;const [name,end]=lines[i].split("<<");const data=[];while(lines[++i]!==end){assert.ok(i<lines.length);data.push(lines[i]);}result[name]=data.join("\n");}return result;}
function outputs(dir,versioning=true){writeFileSync(join(dir,"lzc-private/bootstrap-outputs.json"),JSON.stringify({backend:{value:{bucket:"lzc-dev-state-00000000",region:"eu01"}},backend_credentials:{value:{access_key:"workload-access",secret_key:"workload-secret"}}}));writeFileSync(join(dir,"lzc-private/backend-outputs.json"),JSON.stringify({versioning_enabled:{value:versioning},state_bucket_name:{value:"lzc-dev-state-00000000"}}));}
test("prepare writes private files, keeps credentials out of backend HCL",()=>fixture((dir,env,run)=>{const r=run("management");assert.equal(r.status,0,r.stderr);const v=exported(env.GITHUB_ENV);assert.equal(v.AWS_SECRET_ACCESS_KEY,"management-secret");assert.equal(JSON.parse(v.TF_ENCRYPTION).key_provider.pbkdf2.state.passphrase,base.LZC_STATE_KEY_PLATFORM);const file=join(dir,"lzc-private/platform.backend.hcl");assert.ok(!readFileSync(file,"utf8").includes("secret"));assert.equal(statSync(join(dir,"lzc-private/service-account.json")).mode&0o777,0o600);assert.equal(statSync(join(dir,"lzc-private")).mode&0o777,0o700);}));
test("platform switches to workload backend only after matching versioning proof",()=>fixture((dir,env,run)=>{assert.equal(run("management").status,0);outputs(dir,false);writeFileSync(env.GITHUB_ENV,"");const failed=run("workload");assert.notEqual(failed.status,0);assert.equal(readFileSync(env.GITHUB_ENV,"utf8"),"");outputs(dir);const r=run("workload");assert.equal(r.status,0,r.stderr);assert.equal(exported(env.GITHUB_ENV).AWS_SECRET_ACCESS_KEY,"workload-secret");assert.match(readFileSync(join(dir,"lzc-private/platform.backend.hcl"),"utf8"),/lzc-dev-state-00000000/);}));
test("backend provider gets workload credentials without replacing management S3 credentials",()=>fixture((dir,env,run)=>{assert.equal(run("management",{LZC_ROOT:"backend"}).status,0);outputs(dir);const r=run("workload",{LZC_ROOT:"backend"});assert.equal(r.status,0,r.stderr);const v=exported(env.GITHUB_ENV);assert.equal(v.AWS_SECRET_ACCESS_KEY,"management-secret");assert.equal(v.TF_VAR_storage_secret_key,"workload-secret");}));
test("validation does not need deployment credentials or touch existing local state keys",()=>fixture((_dir,env,run)=>{const patch=Object.fromEntries(Object.keys(base).map(k=>[k,""]));const r=run("validation",{...patch,LZC_ROOT:"seed"});assert.equal(r.status,0,r.stderr);const v=exported(env.GITHUB_ENV);assert.ok(JSON.parse(v.TF_ENCRYPTION).key_provider.pbkdf2.state.passphrase.length>=32);assert.equal(v.AWS_ACCESS_KEY_ID,undefined);}));
