import type { JsonValue, Values } from "./configuration.js";

// Literal HCL strings: user text must never become interpolation or directives.
function quote(value: string): string {
  const escaped = Array.from(value, (character) => {
    if (character === '"') return '\\"';
    if (character === "\\") return "\\\\";
    const code = character.charCodeAt(0);
    if (
      code < 32 ||
      (character.length === 1 && code >= 0xd800 && code <= 0xdfff)
    )
      return `\\u${code.toString(16).padStart(4, "0")}`;
    return character;
  }).join("");
  return `"${escaped.replaceAll("${", () => "$${").replaceAll("%{", () => "%%{")}"`;
}
function render(value: JsonValue, depth: number): string {
  const pad = "  ".repeat(depth);
  const child = "  ".repeat(depth + 1);
  if (typeof value === "string") return quote(value);
  if (value === null || typeof value === "boolean") return String(value);
  if (typeof value === "number") {
    if (!Number.isFinite(value))
      throw new Error("Non-finite configuration number");
    return String(value);
  }
  if (Array.isArray(value)) {
    if (!value.length) return "[]";
    return `[\n${value.map((item) => `${child}${render(item, depth + 1)},`).join("\n")}\n${pad}]`;
  }
  const entries = Object.entries(value).sort(([a], [b]) =>
    a < b ? -1 : a > b ? 1 : 0,
  );
  if (!entries.length) return "{}";
  return `{\n${entries.map(([key, item]) => `${child}${quote(key)} = ${render(item, depth + 1)}`).join("\n")}\n${pad}}`;
}
export function serializeTfvars(values: Values): string {
  const entries = Object.entries(values).sort(([a], [b]) =>
    a < b ? -1 : a > b ? 1 : 0,
  );
  return (
    "# Generated by Landing Zone Configurator (export v1). Edit via the Configurator.\n" +
    entries
      .map(([key, value]) => {
        if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(key))
          throw new Error("Invalid variable name");
        return `${key} = ${render(value, 0)}\n`;
      })
      .join("\n")
  );
}
